const B2C_DATA = [
  {
    id: "dating-profile-audit-rewrite",
    rank: 1,
    category: "Dating / Relationships",
    name: "Dating Profile Audit + Rewrite",
    pain: "People feel unseen, ignored, or poorly represented on apps",
    price: "$29–$79",
    upsell: "$19/mo conversation coach; $149 premium rewrite",
    targetCac: 45,
    score: 8.3,
    tier: "A - Test First",
    ease: 9,
    cacPred: 8,
    profit: 8,
    adSafe: 8,
    urgency: 9,
    noBrand: 8,
    aiFit: 9,
    compGap: 7,
    verdict: "One of the best cold Meta tests; personal, fast, and emotionally obvious",
    metaAngle: "Get a private dating profile audit and rewrite before updating your apps",
    frontProd: "$29 private profile audit",
    aiDeliv: "Photo order, prompt rewrites, bio, opener pack",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe", "OpenAI Vision"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Golden Opportunity Segment: target people who feel below average in this area and want expert-level results without time or cost of traditional options. Price anchors below market alternatives.",
    acquisition: "Meta/Instagram ads to checkout. Cold traffic viable. Target CAC $20-$45.",
    source: "https://www.pewresearch.org/short-reads/2023/02/02/key-findings-about-online-dating-in-the-u-s/"
  },
  {
    id: "wedding-vendor-quote-audit",
    rank: 2,
    category: "Weddings",
    name: "Wedding Vendor Quote Audit",
    pain: "Couples worry they are overpaying before signing contracts",
    price: "$49–$99",
    upsell: "$199 budget rescue; affiliate vendor referrals",
    targetCac: 50,
    score: 8.17,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 8,
    profit: 9,
    adSafe: 8,
    urgency: 9,
    noBrand: 8,
    aiFit: 8,
    compGap: 7,
    verdict: "Strong because one saved vendor mistake can justify the purchase",
    metaAngle: "Before signing another wedding vendor contract, compare your quotes with a budget-saving review",
    frontProd: "$49 quote audit",
    aiDeliv: "Vendor quote comparison, negotiation scripts, cut-list, red flags",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Golden Opportunity Segment: target people who feel below average in this area and want expert-level results without time or cost of traditional options. Price anchors below market alternatives.",
    acquisition: "Meta/Instagram ads to checkout. Cold traffic viable. Target CAC $20-$45.",
    source: "https://www.theknot.com/content/average-wedding-cost"
  },
  {
    id: "resume-linkedin-interview-readiness-audit",
    rank: 3,
    category: "Career / Money",
    name: "Resume + LinkedIn Interview Readiness Audit",
    pain: "Job seekers fear being filtered out before interview",
    price: "$49–$99",
    upsell: "$199–$499 career concierge",
    targetCac: 45,
    score: 8.15,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 8,
    profit: 8,
    adSafe: 9,
    urgency: 8,
    noBrand: 8,
    aiFit: 9,
    compGap: 6,
    verdict: "Easy fulfillment, clear ROI, but competitive category",
    metaAngle: "Turn your resume into a stronger first impression with a private audit and rewrite",
    frontProd: "$49 career audit",
    aiDeliv: "Resume rewrite, LinkedIn rewrite, job-fit score, recruiter DMs",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe", "LinkedIn"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Golden Opportunity Segment: target people who feel below average in this area and want expert-level results without time or cost of traditional options. Price anchors below market alternatives.",
    acquisition: "Meta/Instagram ads to checkout. Cold traffic viable. Target CAC $20-$45.",
    source: "https://www.wordstream.com/blog/facebook-ads-benchmarks-2025"
  },
  {
    id: "dog-behavior-14-day-plan",
    rank: 4,
    category: "Pets",
    name: "Dog Behavior 14-Day Plan",
    pain: "Daily frustration with barking, potty training, leash pulling, chewing",
    price: "$19–$49",
    upsell: "$9–$29/mo training assistant; trainer referral",
    targetCac: 30,
    score: 8.15,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 8,
    profit: 8,
    adSafe: 9,
    urgency: 8,
    noBrand: 8,
    aiFit: 8,
    compGap: 7,
    verdict: "Great no-brand offer if you avoid serious aggression claims",
    metaAngle: "Build a custom training routine for common dog behavior challenges",
    frontProd: "$29 behavior plan",
    aiDeliv: "Daily training schedule, reward plan, mistake checklist, tracker",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Golden Opportunity Segment: target people who feel below average in this area and want expert-level results without time or cost of traditional options. Price anchors below market alternatives.",
    acquisition: "Meta/Instagram ads to checkout. Cold traffic viable. Target CAC $20-$45.",
    source: "https://americanpetproducts.org/news/u.s.-pet-industry-reaches-158-billion-in-2025-poised-for-continued-growth-in-2026"
  },
  {
    id: "room-photo-interior-design-plan",
    rank: 5,
    category: "Home / Decor",
    name: "Room Photo Interior Design Plan",
    pain: "Room feels unfinished, ugly, or hard to decorate",
    price: "$29–$99",
    upsell: "Affiliate furniture/decor; $199 premium design board",
    targetCac: 40,
    score: 8.2,
    tier: "A - Test First",
    ease: 9,
    cacPred: 8,
    profit: 8,
    adSafe: 10,
    urgency: 7,
    noBrand: 9,
    aiFit: 8,
    compGap: 7,
    verdict: "Visual Meta creative can carry this without brand trust",
    metaAngle: "Turn room photos into a finished design plan and shopping list",
    frontProd: "$49 room plan",
    aiDeliv: "Layout, color palette, shopping list, remove/keep list",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "Golden Opportunity Segment: target people who feel below average in this area and want expert-level results without time or cost of traditional options. Price anchors below market alternatives.",
    acquisition: "Meta/Instagram ads to checkout. Cold traffic viable. Target CAC $20-$45.",
    source: ""
  },
  {
    id: "men-s-style-audit",
    rank: 6,
    category: "Style / Status",
    name: "Men's Style Audit",
    pain: "Men want to look sharper for dating, work, and confidence",
    price: "$29–$99",
    upsell: "Affiliate clothing; $199 stylist review",
    targetCac: 40,
    score: 8.0,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 8,
    profit: 8,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 7,
    verdict: "Great creative potential; needs strong before/after sample output",
    metaAngle: "Get a private style audit and outfit plan based on your current wardrobe",
    frontProd: "$49 style audit",
    aiDeliv: "Fit issues, color palette, outfit formulas, shopping list",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "Golden Opportunity Segment: target people who feel below average in this area and want expert-level results without time or cost of traditional options. Price anchors below market alternatives.",
    acquisition: "Meta/Instagram ads to checkout. Cold traffic viable. Target CAC $20-$45.",
    source: ""
  },
  {
    id: "scary-letter-explainer",
    rank: 7,
    category: "Consumer Admin",
    name: "Scary Letter Explainer",
    pain: "People receive confusing official notices and don't know next step",
    price: "$19–$49",
    upsell: "$99 human review; referral partner",
    targetCac: 25,
    score: 7.87,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 8,
    adSafe: 7,
    urgency: 9,
    noBrand: 7,
    aiFit: 9,
    compGap: 8,
    verdict: "High utility; keep it education/admin not legal advice",
    metaAngle: "Turn confusing official letters into a simple next-step checklist",
    frontProd: "$29 letter explainer",
    aiDeliv: "Plain-English summary, deadlines, response draft, checklist",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "travel-refund-complaint-packet",
    rank: 8,
    category: "Travel",
    name: "Travel Refund / Complaint Packet",
    pain: "Travelers feel wronged by airline, hotel, cruise, Airbnb, baggage issue",
    price: "$19–$79",
    upsell: "$99 concierge filing help",
    targetCac: 25,
    score: 7.72,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 8,
    adSafe: 8,
    urgency: 8,
    noBrand: 7,
    aiFit: 9,
    compGap: 7,
    verdict: "Better for search intent, but Meta works with broad travel frustration creative",
    metaAngle: "Create a stronger travel refund request with a guided document packet",
    frontProd: "$29 refund packet",
    aiDeliv: "Timeline, evidence checklist, refund request, escalation path",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "subscription-leak-audit",
    rank: 9,
    category: "Finance / Budgeting",
    name: "Subscription Leak Audit",
    pain: "Consumers lose money to forgotten subscriptions and hard cancellations",
    price: "$9–$39",
    upsell: "$49–$99 cancellation concierge",
    targetCac: 15,
    score: 7.78,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 8,
    profit: 7,
    adSafe: 8,
    urgency: 8,
    noBrand: 8,
    aiFit: 8,
    compGap: 7,
    verdict: "Low price improves cold conversion; fulfillment must be frictionless",
    metaAngle: "Find recurring charges faster with a private statement review",
    frontProd: "$19 recurring-charge audit",
    aiDeliv: "Recurring charge list, cancellation links, scripts, reminders",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: "https://www.ftc.gov/news-events/news/press-releases/2024/10/federal-trade-commission-announces-final-click-cancel-rule-making-it-easier-consumers-end-recurring"
  },
  {
    id: "teen-major-career-path-report",
    rank: 10,
    category: "College / Parents",
    name: "Teen Major + Career Path Report",
    pain: "Parents and teens feel uncertain about college direction and ROI",
    price: "$29–$99",
    upsell: "$199 college planning bundle",
    targetCac: 25,
    score: 7.72,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 8,
    adSafe: 9,
    urgency: 8,
    noBrand: 7,
    aiFit: 8,
    compGap: 7,
    verdict: "Good parent anxiety offer; avoid overpromising career outcomes",
    metaAngle: "Build a personalized college-major comparison report for your student",
    frontProd: "$49 major finder report",
    aiDeliv: "Major comparison, career paths, school shortlist, tour questions",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe", "LinkedIn"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "moving-plan-vendor-script",
    rank: 11,
    category: "Moving / Relocation",
    name: "Moving Plan + Vendor Script",
    pain: "Moving is chaotic and easy to forget details",
    price: "$19–$79",
    upsell: "Mover/storage affiliate; $99 concierge",
    targetCac: 20,
    score: 7.85,
    tier: "B - Worth Testing",
    ease: 10,
    cacPred: 7,
    profit: 7,
    adSafe: 10,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 6,
    verdict: "Low-risk and easy, but pain may be less intense than top ideas",
    metaAngle: "Get a personalized moving checklist, budget, and vendor script",
    frontProd: "$29 move plan",
    aiDeliv: "Timeline, packing plan, utility checklist, vendor quote script",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "family-caregiver-command-center",
    rank: 12,
    category: "Caregiving",
    name: "Family Caregiver Command Center",
    pain: "Adult children are overwhelmed coordinating parent care",
    price: "$49–$149",
    upsell: "$19/mo care assistant; eldercare referrals",
    targetCac: 40,
    score: 7.34,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 8,
    adSafe: 7,
    urgency: 9,
    noBrand: 6,
    aiFit: 8,
    compGap: 8,
    verdict: "Huge pain, but trust/privacy sensitivity lowers cold Meta predictability",
    metaAngle: "Organize family caregiving tasks into one simple weekly plan",
    frontProd: "$49 care organizer",
    aiDeliv: "Care calendar, medication tracker, sibling task plan, doctor questions",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: "https://www.aarp.org/pri/topics/ltss/family-caregiving/caregiving-in-the-us-2025/"
  },
  {
    id: "baby-registry-audit",
    rank: 13,
    category: "Parenting",
    name: "Baby Registry Audit",
    pain: "New parents are overwhelmed by what to buy and what not to buy",
    price: "$19–$79",
    upsell: "Affiliate products; $149 nursery setup plan",
    targetCac: 30,
    score: 7.93,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 8,
    profit: 7,
    adSafe: 9,
    urgency: 8,
    noBrand: 8,
    aiFit: 8,
    compGap: 6,
    verdict: "Highly visual and purchase-driven; affiliate upside",
    metaAngle: "Create a practical baby registry plan by budget and lifestyle",
    frontProd: "$29 registry audit",
    aiDeliv: "Registry cleanup, must-have list, budget tiers, missing items",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "wedding-speech-vow-writer",
    rank: 14,
    category: "Events",
    name: "Wedding Speech / Vow Writer",
    pain: "People fear embarrassing themselves in emotional public moments",
    price: "$19–$49",
    upsell: "$99 premium rewrite",
    targetCac: 20,
    score: 8.18,
    tier: "B - Worth Testing",
    ease: 10,
    cacPred: 8,
    profit: 7,
    adSafe: 10,
    urgency: 8,
    noBrand: 8,
    aiFit: 9,
    compGap: 5,
    verdict: "Very easy to launch; low AOV means upsell/volume matters",
    metaAngle: "Get a polished wedding speech or vow draft from your story",
    frontProd: "$19 speech kit",
    aiDeliv: "Speech outline, polished draft, rehearsal tips, toast length guide",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Golden Opportunity Segment: target people who feel below average in this area and want expert-level results without time or cost of traditional options. Price anchors below market alternatives.",
    acquisition: "Meta/Instagram ads to checkout. Cold traffic viable. Target CAC $20-$45.",
    source: "https://www.theknot.com/content/average-wedding-cost"
  },
  {
    id: "funeral-cost-planning-checklist",
    rank: 15,
    category: "Funeral / Family",
    name: "Funeral Cost Planning Checklist",
    pain: "Families are making expensive decisions under grief and pressure",
    price: "$19–$79",
    upsell: "$149 family planning packet",
    targetCac: 25,
    score: 6.94,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 5,
    profit: 7,
    adSafe: 7,
    urgency: 9,
    noBrand: 5,
    aiFit: 8,
    compGap: 8,
    verdict: "Real pain, but sensitive and trust-heavy for cold Meta",
    metaAngle: "Prepare a simple funeral planning checklist before calling providers",
    frontProd: "$29 funeral planning kit",
    aiDeliv: "GPL checklist, call script, cost comparison worksheet, obituary draft",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: "https://www.ftc.gov/business-guidance/resources/complying-funeral-rule"
  },
  {
    id: "first-time-homebuyer-readiness-plan",
    rank: 16,
    category: "Homeownership",
    name: "First-Time Homebuyer Readiness Plan",
    pain: "Buyers feel confused about what to fix before applying",
    price: "$29–$99",
    upsell: "Lender/realtor referral; $199 consult",
    targetCac: 30,
    score: 6.99,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 8,
    adSafe: 6,
    urgency: 8,
    noBrand: 6,
    aiFit: 8,
    compGap: 7,
    verdict: "Good offer but finance/housing ads need careful policy handling",
    metaAngle: "Prepare for a first home purchase with a personalized readiness checklist",
    frontProd: "$49 readiness plan",
    aiDeliv: "Document checklist, lender questions, 90-day prep, affordability worksheet",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: "https://www.nar.realtor/newsroom/first-time-home-buyer-share-falls-to-historic-low-of-21-median-age-rises-to-40"
  },
  {
    id: "skincare-routine-simplifier",
    rank: 17,
    category: "Beauty / Status",
    name: "Skincare Routine Simplifier",
    pain: "Consumers are overwhelmed by products and inconsistent routines",
    price: "$19–$79",
    upsell: "Affiliate skincare; $19/mo routine assistant",
    targetCac: 30,
    score: 7.8,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 8,
    profit: 8,
    adSafe: 8,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 6,
    verdict: "Strong, but health/appearance wording needs policy-safe framing",
    metaAngle: "Build a simplified skincare routine from the products already on your shelf",
    frontProd: "$29 routine plan",
    aiDeliv: "Routine audit, product order, ingredient conflicts, simple AM/PM plan",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "meal-prep-plan-for-busy-professionals",
    rank: 18,
    category: "Fitness / Health Adjacent",
    name: "Meal Prep Plan for Busy Professionals",
    pain: "People want easier healthy eating without complex dieting",
    price: "$19–$49",
    upsell: "$9/mo meal planner",
    targetCac: 20,
    score: 7.63,
    tier: "B - Worth Testing",
    ease: 10,
    cacPred: 8,
    profit: 7,
    adSafe: 7,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Easy launch but commoditized; needs strong niche angle",
    metaAngle: "Create a simple weekly meal prep plan based on your schedule and preferences",
    frontProd: "$29 meal prep plan",
    aiDeliv: "Grocery list, recipes, prep schedule, macro-light options",
    platforms: ["Spoonacular API", "n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "bill-negotiation-prep-kit",
    rank: 19,
    category: "Finance / Consumer",
    name: "Bill Negotiation Prep Kit",
    pain: "Consumers want lower bills but hate calling providers",
    price: "$19–$49",
    upsell: "Percentage of savings; concierge",
    targetCac: 20,
    score: 7.4,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 7,
    adSafe: 8,
    urgency: 8,
    noBrand: 7,
    aiFit: 8,
    compGap: 6,
    verdict: "Could work; subscription audit is cleaner and more concrete",
    metaAngle: "Create scripts and a plan for reviewing household bills",
    frontProd: "$29 negotiation kit",
    aiDeliv: "Provider call script, comparison checklist, cancellation threat script",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "child-homework-recovery-plan",
    rank: 20,
    category: "Education",
    name: "Child Homework Recovery Plan",
    pain: "Parents need a plan when a child is slipping in a subject",
    price: "$29–$99",
    upsell: "$19/mo AI tutor assistant",
    targetCac: 30,
    score: 7.52,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 8,
    adSafe: 8,
    urgency: 8,
    noBrand: 7,
    aiFit: 8,
    compGap: 6,
    verdict: "Solid parent offer; avoid implying a child has a disability or diagnosis",
    metaAngle: "Create a 30-day study support plan for your student",
    frontProd: "$49 academic plan",
    aiDeliv: "30-day study plan, teacher email, parent routine, practice prompts",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "personal-online-presence-audit",
    rank: 21,
    category: "Identity / Social",
    name: "Personal Online Presence Audit",
    pain: "People want to look better online for dating, jobs, or social credibility",
    price: "$29–$99",
    upsell: "$199 personal brand cleanup",
    targetCac: 20,
    score: 7.62,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 8,
    adSafe: 8,
    urgency: 8,
    noBrand: 7,
    aiFit: 8,
    compGap: 7,
    verdict: "Good broad offer; positioning must be specific to convert cold",
    metaAngle: "Get a private audit of your online first impression",
    frontProd: "$49 online audit",
    aiDeliv: "Bio rewrites, social cleanup checklist, LinkedIn/dating alignment",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "lease-letter-renter-notice-explainer",
    rank: 22,
    category: "Legal-adjacent Admin",
    name: "Lease Letter / Renter Notice Explainer",
    pain: "Renters need to understand notices, lease clauses, or move-out charges",
    price: "$19–$49",
    upsell: "$99 human review/referral",
    targetCac: 25,
    score: 7.27,
    tier: "C - Needs Strong Angle",
    ease: 8,
    cacPred: 6,
    profit: 7,
    adSafe: 6,
    urgency: 9,
    noBrand: 6,
    aiFit: 8,
    compGap: 8,
    verdict: "High pain but legal-adjacent; keep as organization not legal advice",
    metaAngle: "Turn lease notices into a clear next-step checklist",
    frontProd: "$29 renter letter kit",
    aiDeliv: "Plain-English summary, deadline checklist, landlord email draft",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "car-buying-negotiation-kit",
    rank: 23,
    category: "Auto",
    name: "Car Buying Negotiation Kit",
    pain: "Car shoppers fear getting overcharged or upsold at dealership",
    price: "$29–$99",
    upsell: "Auto insurance/lender/referral",
    targetCac: 35,
    score: 7.62,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 8,
    adSafe: 8,
    urgency: 8,
    noBrand: 7,
    aiFit: 8,
    compGap: 7,
    verdict: "Strong pain and clear savings; competition from calculators but not personalized packets",
    metaAngle: "Review a car quote before signing and get a negotiation plan",
    frontProd: "$49 car deal review",
    aiDeliv: "Dealer fee audit, negotiation script, financing checklist",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "home-repair-quote-comparison",
    rank: 24,
    category: "Home Services",
    name: "Home Repair Quote Comparison",
    pain: "Homeowners get multiple confusing contractor quotes",
    price: "$29–$99",
    upsell: "Contractor referral; $199 project planner",
    targetCac: 30,
    score: 7.62,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 8,
    adSafe: 8,
    urgency: 8,
    noBrand: 7,
    aiFit: 8,
    compGap: 7,
    verdict: "Works well for roofing/HVAC/plumbing quotes; very practical",
    metaAngle: "Compare home repair quotes before choosing a contractor",
    frontProd: "$49 quote comparison",
    aiDeliv: "Scope comparison, missing line items, questions, negotiation scripts",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "breakup-dating-reset-plan",
    rank: 25,
    category: "Relationships",
    name: "Breakup / Dating Reset Plan",
    pain: "Newly single people want confidence, routine, style, and social reset",
    price: "$29–$99",
    upsell: "$19/mo accountability assistant",
    targetCac: 20,
    score: 6.87,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 7,
    adSafe: 6,
    urgency: 8,
    noBrand: 6,
    aiFit: 8,
    compGap: 7,
    verdict: "Emotional but sensitive; ad angle must avoid asserting relationship status",
    metaAngle: "Create a private post-breakup life reset plan",
    frontProd: "$49 reset plan",
    aiDeliv: "30-day plan, dating profile, wardrobe basics, social calendar",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "ai-itinerary-rescue",
    rank: 26,
    category: "Travel",
    name: "AI Itinerary Rescue",
    pain: "Travel planners are overwhelmed by options and logistics",
    price: "$29–$99",
    upsell: "Affiliate bookings; $149 concierge plan",
    targetCac: 20,
    score: 7.5,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 7,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Easy launch but crowded; niche by family trips, girls trips, Disney, cruises",
    metaAngle: "Turn destination ideas into a practical itinerary and backup plan",
    frontProd: "$39 itinerary plan",
    aiDeliv: "Daily itinerary, restaurant map, booking checklist, backups",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "birthday-party-plan-for-kids",
    rank: 27,
    category: "Parenting / Events",
    name: "Birthday Party Plan for Kids",
    pain: "Parents want a good party without planning chaos",
    price: "$19–$59",
    upsell: "Affiliate party supplies; $99 premium",
    targetCac: 20,
    score: 7.93,
    tier: "B - Worth Testing",
    ease: 10,
    cacPred: 8,
    profit: 7,
    adSafe: 10,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Simple and visual; lower urgency/AOV but easy to test",
    metaAngle: "Create a complete birthday party plan by age, budget, and theme",
    frontProd: "$29 party plan",
    aiDeliv: "Theme, shopping list, timeline, games, invite text",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "dinner-party-hosting-plan",
    rank: 28,
    category: "Food / Hosting",
    name: "Dinner Party / Hosting Plan",
    pain: "People want to host but feel disorganized or unimpressive",
    price: "$19–$59",
    upsell: "Affiliate products; $99 premium",
    targetCac: 20,
    score: 7.6,
    tier: "B - Worth Testing",
    ease: 10,
    cacPred: 7,
    profit: 7,
    adSafe: 10,
    urgency: 6,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Good lifestyle offer; needs aspirational creative",
    metaAngle: "Create a complete hosting plan for your next gathering",
    frontProd: "$29 hosting plan",
    aiDeliv: "Menu, grocery list, timeline, seating, music, conversation prompts",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "sermon-bible-study-personalizer",
    rank: 29,
    category: "Faith",
    name: "Sermon / Bible Study Personalizer",
    pain: "Christians want to apply sermons/scripture to daily life",
    price: "$9–$49",
    upsell: "$9/mo study assistant; church group packs",
    targetCac: 30,
    score: 7.6,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 7,
    adSafe: 9,
    urgency: 7,
    noBrand: 7,
    aiFit: 9,
    compGap: 6,
    verdict: "Niche and emotional; ad policy around religion requires softer targeting/wording",
    metaAngle: "Turn a sermon or topic into a personal Bible study plan",
    frontProd: "$19 study pack",
    aiDeliv: "Summary, scriptures, reflection questions, prayer/action plan",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "timeshare-exit-readiness-packet",
    rank: 30,
    category: "Consumer Protection",
    name: "Timeshare Exit Readiness Packet",
    pain: "Owners feel trapped by fees and fear scams",
    price: "$49–$199",
    upsell: "$499 human review/referral",
    targetCac: 20,
    score: 6.38,
    tier: "D - Search Only",
    ease: 5,
    cacPred: 4,
    profit: 8,
    adSafe: 5,
    urgency: 9,
    noBrand: 4,
    aiFit: 8,
    compGap: 9,
    verdict: "Good search offer, not ideal for cold Meta due scam/legal trust issues",
    metaAngle: "Prepare your timeshare documents before talking to an exit company",
    frontProd: "$99 readiness packet",
    aiDeliv: "Contract summary, resort call script, scam checklist, options organizer",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: "https://consumer.ftc.gov/articles/timeshares-vacation-clubs-and-related-scams"
  },
  {
    id: "scam-recovery-fraud-report-organizer",
    rank: 31,
    category: "Consumer Protection",
    name: "Scam Recovery / Fraud Report Organizer",
    pain: "Victims need to organize evidence and reporting steps",
    price: "$29–$99",
    upsell: "$199 advocate review/referral",
    targetCac: 25,
    score: 6.81,
    tier: "C - Needs Strong Angle",
    ease: 6,
    cacPred: 5,
    profit: 8,
    adSafe: 6,
    urgency: 9,
    noBrand: 5,
    aiFit: 8,
    compGap: 8,
    verdict: "Huge pain; sensitive and trust-heavy, better search/retargeting than cold Meta",
    metaAngle: "Organize scam evidence and next steps in one packet",
    frontProd: "$49 scam report organizer",
    aiDeliv: "Timeline, evidence checklist, reporting links, bank call script",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: "https://www.fbi.gov/news/press-releases/fbi-releases-annual-internet-crime-report"
  },
  {
    id: "medical-bill-review-prep",
    rank: 32,
    category: "Health Admin",
    name: "Medical Bill Review Prep",
    pain: "Patients are confused by bills and payment options",
    price: "$29–$99",
    upsell: "$199 concierge paperwork",
    targetCac: 20,
    score: 6.61,
    tier: "C - Needs Strong Angle",
    ease: 6,
    cacPred: 5,
    profit: 8,
    adSafe: 5,
    urgency: 9,
    noBrand: 5,
    aiFit: 8,
    compGap: 7,
    verdict: "Useful but healthcare privacy/trust reduces Meta cold predictability",
    metaAngle: "Prepare questions and documents before calling medical billing",
    frontProd: "$49 bill review prep",
    aiDeliv: "Bill summary, question list, charity care checklist, call script",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "warranty-denial-appeal-packet",
    rank: 33,
    category: "Insurance / Warranty",
    name: "Warranty Denial Appeal Packet",
    pain: "Consumers feel denied unfairly and don't know how to appeal",
    price: "$29–$99",
    upsell: "$199 human review/referral",
    targetCac: 25,
    score: 7.19,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 8,
    adSafe: 7,
    urgency: 8,
    noBrand: 6,
    aiFit: 9,
    compGap: 7,
    verdict: "Document upload offer is strong; careful with legal claims",
    metaAngle: "Create a structured warranty appeal packet from your denial letter",
    frontProd: "$49 appeal packet",
    aiDeliv: "Denial summary, evidence checklist, appeal letter, escalation path",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "hoa-fine-violation-response-kit",
    rank: 34,
    category: "HOA / Home",
    name: "HOA Fine / Violation Response Kit",
    pain: "Homeowners are frustrated by HOA notices and fines",
    price: "$19–$79",
    upsell: "$149 premium packet/referral",
    targetCac: 20,
    score: 7.34,
    tier: "C - Needs Strong Angle",
    ease: 8,
    cacPred: 6,
    profit: 8,
    adSafe: 7,
    urgency: 8,
    noBrand: 6,
    aiFit: 8,
    compGap: 8,
    verdict: "Very niche and painful; good landing page fit if ad-safe",
    metaAngle: "Turn an HOA notice into a clear response checklist",
    frontProd: "$39 HOA response kit",
    aiDeliv: "Notice summary, response draft, evidence checklist, deadline tracker",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "aging-parent-home-safety-checklist",
    rank: 35,
    category: "Seniors / Family",
    name: "Aging Parent Home Safety Checklist",
    pain: "Families worry about falls, clutter, medications, emergency readiness",
    price: "$29–$99",
    upsell: "Affiliate safety products; home care referrals",
    targetCac: 30,
    score: 6.97,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 7,
    adSafe: 7,
    urgency: 8,
    noBrand: 6,
    aiFit: 8,
    compGap: 7,
    verdict: "Solid, but trust and age/personal attributes affect ad wording",
    metaAngle: "Create a home safety checklist for an aging loved one's house",
    frontProd: "$39 safety checklist",
    aiDeliv: "Room-by-room checklist, supply list, family task plan",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: "https://www.aarp.org/pri/topics/ltss/family-caregiving/caregiving-in-the-us-2025/"
  },
  {
    id: "first-date-planner",
    rank: 36,
    category: "Dating / Relationships",
    name: "First Date Planner",
    pain: "People want low-pressure creative date ideas and conversation flow",
    price: "$9–$39",
    upsell: "Monthly dating assistant",
    targetCac: 20,
    score: 7.48,
    tier: "B - Worth Testing",
    ease: 10,
    cacPred: 7,
    profit: 6,
    adSafe: 10,
    urgency: 6,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Easy and fun, but lower pain/price than profile audit",
    metaAngle: "Create a thoughtful date plan by city, vibe, and budget",
    frontProd: "$19 date plan",
    aiDeliv: "Date venue ideas, conversation prompts, logistics checklist",
    platforms: ["OpenAI Vision", "n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "weekend-plan-concierge",
    rank: 37,
    category: "Local Experiences",
    name: "Weekend Plan Concierge",
    pain: "People want curated local plans without research",
    price: "$9–$49",
    upsell: "Subscription; affiliate bookings",
    targetCac: 20,
    score: 6.9,
    tier: "C - Needs Strong Angle",
    ease: 9,
    cacPred: 6,
    profit: 6,
    adSafe: 10,
    urgency: 5,
    noBrand: 8,
    aiFit: 8,
    compGap: 4,
    verdict: "Likely harder to profit on paid CAC unless niche/high AOV",
    metaAngle: "Turn your weekend preferences into a ready-to-follow plan",
    frontProd: "$19 weekend plan",
    aiDeliv: "Itinerary, restaurant picks, reservation scripts, backup plans",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "declutter-plan-from-room-photos",
    rank: 38,
    category: "Home / Organizing",
    name: "Declutter Plan from Room Photos",
    pain: "Consumers want to organize a room but don't know where to start",
    price: "$19–$59",
    upsell: "Affiliate storage; $99 whole-home plan",
    targetCac: 30,
    score: 7.78,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 8,
    profit: 7,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 6,
    verdict: "Visual and practical; strong for ADHD-friendly or busy-parent angles if policy-safe",
    metaAngle: "Turn cluttered room photos into a step-by-step reset plan",
    frontProd: "$29 declutter plan",
    aiDeliv: "Zone plan, keep/donate/trash rules, storage shopping list",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "mold-concern-prep-checklist",
    rank: 39,
    category: "Home / Mold Adjacent",
    name: "Mold Concern Prep Checklist",
    pain: "Homeowners/renters want to know what to document before calling pros",
    price: "$19–$79",
    upsell: "Inspector/remediator referral",
    targetCac: 20,
    score: 6.79,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 8,
    adSafe: 5,
    urgency: 8,
    noBrand: 6,
    aiFit: 7,
    compGap: 7,
    verdict: "Good search offer; Meta health claims and fear angle need restraint",
    metaAngle: "Prepare your mold documentation and questions before calling a pro",
    frontProd: "$29 mold concern prep",
    aiDeliv: "Photo/document checklist, questions for inspector, remediation estimate prep",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "couples-conversation-planner",
    rank: 40,
    category: "Relationships / Marriage",
    name: "Couples Conversation Planner",
    pain: "Couples need structured conversations about money, future, conflict",
    price: "$19–$59",
    upsell: "$19/mo relationship prompts",
    targetCac: 20,
    score: 6.77,
    tier: "C - Needs Strong Angle",
    ease: 8,
    cacPred: 6,
    profit: 7,
    adSafe: 6,
    urgency: 7,
    noBrand: 6,
    aiFit: 8,
    compGap: 6,
    verdict: "Sensitive; possible but not as clean as dating profile audit",
    metaAngle: "Create a guided relationship conversation plan for important topics",
    frontProd: "$29 conversation kit",
    aiDeliv: "Question set, agenda, scripts, shared notes template",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "personal-cashflow-cleanup-plan",
    rank: 41,
    category: "Finance / Budgeting",
    name: "Personal Cashflow Cleanup Plan",
    pain: "People need clarity on bills, spending, and priorities",
    price: "$29–$99",
    upsell: "$19/mo budget assistant",
    targetCac: 20,
    score: 6.57,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 7,
    adSafe: 5,
    urgency: 8,
    noBrand: 6,
    aiFit: 8,
    compGap: 5,
    verdict: "Financial-personal-attribute policy risk; better via lead magnet/retargeting",
    metaAngle: "Organize monthly bills and spending into a simple plan",
    frontProd: "$39 cashflow plan",
    aiDeliv: "Spending categories, bill calendar, cut list, payment plan",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "interview-answer-builder",
    rank: 42,
    category: "Career / School",
    name: "Interview Answer Builder",
    pain: "Applicants need stronger answers for upcoming interviews",
    price: "$19–$79",
    upsell: "$99 mock interview",
    targetCac: 20,
    score: 7.9,
    tier: "B - Worth Testing",
    ease: 10,
    cacPred: 7,
    profit: 7,
    adSafe: 9,
    urgency: 8,
    noBrand: 8,
    aiFit: 9,
    compGap: 5,
    verdict: "Easy to launch; direct urgency if targeting job seekers carefully",
    metaAngle: "Build role-specific interview answers from your experience",
    frontProd: "$29 interview kit",
    aiDeliv: "STAR stories, role-specific questions, practice prompts",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "college-essay-brainstorm-draft-coach",
    rank: 43,
    category: "College / Essays",
    name: "College Essay Brainstorm + Draft Coach",
    pain: "Students/parents need essay direction and polished story",
    price: "$49–$149",
    upsell: "$299 human editor review",
    targetCac: 25,
    score: 7.64,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 9,
    adSafe: 8,
    urgency: 8,
    noBrand: 7,
    aiFit: 8,
    compGap: 6,
    verdict: "Seasonal but high willingness to pay; avoid plagiarism/full ghostwriting claims",
    metaAngle: "Turn student experiences into stronger college essay ideas",
    frontProd: "$49 essay coach",
    aiDeliv: "Brainstorm, outline, draft feedback, authenticity checklist",
    platforms: ["Vapi", "Telnyx"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "apartment-hunt-decision-matrix",
    rank: 44,
    category: "Real Estate / Moving",
    name: "Apartment Hunt Decision Matrix",
    pain: "Renters compare units, commute, costs, deposits, hidden fees",
    price: "$19–$59",
    upsell: "Locator referral; $99 concierge",
    targetCac: 20,
    score: 7.4,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 7,
    adSafe: 8,
    urgency: 7,
    noBrand: 7,
    aiFit: 8,
    compGap: 6,
    verdict: "Practical but lower emotional hook unless positioned around avoiding bad lease decisions",
    metaAngle: "Compare apartments side-by-side before submitting an application",
    frontProd: "$29 apartment decision kit",
    aiDeliv: "Comparison sheet, question list, budget, tour checklist",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "photo-selection-audit-for-dating-linkedin",
    rank: 45,
    category: "Identity / Photos",
    name: "Photo Selection Audit for Dating/LinkedIn",
    pain: "People don't know which photos make the best first impression",
    price: "$9–$39",
    upsell: "$79 full profile audit",
    targetCac: 20,
    score: 8.03,
    tier: "B - Worth Testing",
    ease: 10,
    cacPred: 8,
    profit: 7,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 9,
    compGap: 6,
    verdict: "Very easy tripwire; good lead-in to dating/career/style upsells",
    metaAngle: "Get a private photo ranking for profiles and first impressions",
    frontProd: "$19 photo ranking",
    aiDeliv: "Rank photos, explain why, reorder, suggest missing shots",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "Golden Opportunity Segment: target people who feel below average in this area and want expert-level results without time or cost of traditional options. Price anchors below market alternatives.",
    acquisition: "Meta/Instagram ads to checkout. Cold traffic viable. Target CAC $20-$45.",
    source: "https://www.pewresearch.org/short-reads/2023/02/02/key-findings-about-online-dating-in-the-u-s/"
  },
  {
    id: "bachelorette-girls-trip-planner",
    rank: 46,
    category: "Events",
    name: "Bachelorette / Girls Trip Planner",
    pain: "Group trips create coordination headaches and budget conflict",
    price: "$29–$99",
    upsell: "Affiliate travel; premium concierge",
    targetCac: 20,
    score: 7.5,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 7,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Good Meta visual creative; less universal than wedding quote audit",
    metaAngle: "Create a coordinated group trip plan with budget and itinerary",
    frontProd: "$39 group trip plan",
    aiDeliv: "Itinerary, budget split, RSVP texts, booking checklist",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "pantry-to-meal-plan",
    rank: 47,
    category: "Food / Health Adjacent",
    name: "Pantry-to-Meal Plan",
    pain: "People waste groceries and don't know what to cook",
    price: "$9–$39",
    upsell: "$9/mo meal assistant",
    targetCac: 20,
    score: 7.38,
    tier: "C - Needs Strong Angle",
    ease: 10,
    cacPred: 7,
    profit: 6,
    adSafe: 9,
    urgency: 6,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Easy but lower AOV; needs subscription or affiliate upside",
    metaAngle: "Turn pantry photos into meals for the week",
    frontProd: "$19 pantry plan",
    aiDeliv: "Meals from current pantry, grocery add-ons, prep schedule",
    platforms: ["Spoonacular API", "n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "home-maintenance-calendar",
    rank: 48,
    category: "Home / Property",
    name: "Home Maintenance Calendar",
    pain: "Homeowners forget seasonal maintenance and get surprise repairs",
    price: "$19–$79",
    upsell: "Affiliate/referral home services",
    targetCac: 20,
    score: 7.6,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 7,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 6,
    verdict: "Practical, broad, and safe; pain less urgent unless tied to repair prevention",
    metaAngle: "Build a custom home maintenance calendar for your property",
    frontProd: "$29 home calendar",
    aiDeliv: "Seasonal checklist, reminders, vendor questions, supply list",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "name-change-packet",
    rank: 49,
    category: "Consumer Admin",
    name: "Name Change Packet",
    pain: "Newly married/divorced people need to update IDs/accounts",
    price: "$19–$79",
    upsell: "$99 concierge assistance",
    targetCac: 20,
    score: 7.4,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 7,
    adSafe: 7,
    urgency: 7,
    noBrand: 7,
    aiFit: 8,
    compGap: 7,
    verdict: "Good life-event niche; ad wording must avoid personal status assumptions",
    metaAngle: "Create a personalized name-change checklist and message pack",
    frontProd: "$29 name change packet",
    aiDeliv: "Checklist, forms links, email templates, timeline",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "1099-freelancer-tax-prep-organizer",
    rank: 50,
    category: "Finance / Taxes",
    name: "1099 Freelancer Tax Prep Organizer",
    pain: "Freelancers need expenses organized before tax filing",
    price: "$29–$99",
    upsell: "Bookkeeping/CPA referral",
    targetCac: 20,
    score: 6.89,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 8,
    adSafe: 6,
    urgency: 8,
    noBrand: 6,
    aiFit: 8,
    compGap: 6,
    verdict: "Seasonal; must avoid tax advice without proper disclaimer",
    metaAngle: "Organize freelance tax documents before meeting your preparer",
    frontProd: "$49 tax organizer",
    aiDeliv: "Expense categories, doc checklist, CPA question list",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "holiday-gift-finder-from-recipient-profile",
    rank: 51,
    category: "Home / Events",
    name: "Holiday Gift Finder from Recipient Profile",
    pain: "Shoppers struggle to pick meaningful gifts",
    price: "$9–$39",
    upsell: "Affiliate products; $9/mo gifting assistant",
    targetCac: 20,
    score: 7.48,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 6,
    adSafe: 10,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Good affiliate potential but seasonal and low front-end AOV",
    metaAngle: "Create a personalized gift plan by person, budget, and occasion",
    frontProd: "$19 gift plan",
    aiDeliv: "Gift shortlist, message/card, budget tiers, purchase links",
    platforms: ["OpenAI Vision"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "summer-camp-finder-decision-sheet",
    rank: 52,
    category: "Parenting",
    name: "Summer Camp Finder / Decision Sheet",
    pain: "Parents compare costs, schedules, safety, interests",
    price: "$19–$59",
    upsell: "Affiliate/referral with camps",
    targetCac: 20,
    score: 7.07,
    tier: "C - Needs Strong Angle",
    ease: 8,
    cacPred: 6,
    profit: 7,
    adSafe: 8,
    urgency: 7,
    noBrand: 7,
    aiFit: 8,
    compGap: 6,
    verdict: "Seasonal but strong parent utility",
    metaAngle: "Compare summer camps by schedule, budget, and child interests",
    frontProd: "$29 camp comparison",
    aiDeliv: "Camp shortlist, questions, cost comparison, calendar",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "diy-project-planner",
    rank: 53,
    category: "Home / DIY",
    name: "DIY Project Planner",
    pain: "Homeowners want to complete a project without getting overwhelmed",
    price: "$19–$59",
    upsell: "Affiliate tools/materials",
    targetCac: 20,
    score: 7.5,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 7,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Safe and broad, but may skew to free content unless very personalized",
    metaAngle: "Turn a home project idea into a step-by-step plan and shopping list",
    frontProd: "$29 DIY project plan",
    aiDeliv: "Materials list, steps, timeline, tool list, safety checklist",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "small-claims-prep-organizer",
    rank: 54,
    category: "Small Claims",
    name: "Small Claims Prep Organizer",
    pain: "Consumers need to organize facts, evidence, and timeline",
    price: "$29–$99",
    upsell: "$199 human review/referral",
    targetCac: 15,
    score: 6.71,
    tier: "C - Needs Strong Angle",
    ease: 6,
    cacPred: 5,
    profit: 8,
    adSafe: 5,
    urgency: 9,
    noBrand: 5,
    aiFit: 8,
    compGap: 8,
    verdict: "Strong pain but legal-adjacent and trust-heavy; search > Meta",
    metaAngle: "Organize your small-claims evidence into a clear prep packet",
    frontProd: "$49 prep organizer",
    aiDeliv: "Timeline, evidence checklist, claim narrative, court-day checklist",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "car-maintenance-mechanic-quote-explainer",
    rank: 55,
    category: "Auto",
    name: "Car Maintenance / Mechanic Quote Explainer",
    pain: "Drivers don't understand mechanic quotes and fear overpaying",
    price: "$29–$79",
    upsell: "Mechanic referral; concierge",
    targetCac: 20,
    score: 7.62,
    tier: "B - Worth Testing",
    ease: 8,
    cacPred: 7,
    profit: 8,
    adSafe: 8,
    urgency: 8,
    noBrand: 7,
    aiFit: 8,
    compGap: 7,
    verdict: "Practical, broad, and pain-driven; strong with photo/upload funnel",
    metaAngle: "Review a mechanic quote before approving repairs",
    frontProd: "$39 mechanic quote review",
    aiDeliv: "Quote summary, questions, common parts/labor explanation",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "home-insurance-renewal-review-prep",
    rank: 56,
    category: "Insurance",
    name: "Home Insurance Renewal Review Prep",
    pain: "Homeowners face premium hikes and confusing renewals",
    price: "$29–$99",
    upsell: "Agent referral",
    targetCac: 15,
    score: 6.46,
    tier: "D - Search Only",
    ease: 6,
    cacPred: 5,
    profit: 8,
    adSafe: 5,
    urgency: 8,
    noBrand: 5,
    aiFit: 8,
    compGap: 7,
    verdict: "Potentially valuable but finance/insurance ads and trust reduce cold CAC confidence",
    metaAngle: "Prepare questions and a comparison worksheet for insurance renewal",
    frontProd: "$49 renewal prep",
    aiDeliv: "Coverage summary, question list, quote comparison worksheet",
    platforms: ["n8n", "GPT-4o", "Typeform", "Stripe"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "difficult-family-conversation-script",
    rank: 57,
    category: "Relationships / Family",
    name: "Difficult Family Conversation Script",
    pain: "People need words for boundaries, caregiving, money, conflict",
    price: "$19–$59",
    upsell: "$19/mo communication assistant",
    targetCac: 20,
    score: 7.02,
    tier: "C - Needs Strong Angle",
    ease: 8,
    cacPred: 6,
    profit: 7,
    adSafe: 6,
    urgency: 8,
    noBrand: 6,
    aiFit: 9,
    compGap: 6,
    verdict: "Emotionally strong but ad-safe framing is harder",
    metaAngle: "Create a thoughtful script for an important family conversation",
    frontProd: "$29 script kit",
    aiDeliv: "Conversation plan, scripts, text drafts, de-escalation wording",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "lost-password-digital-estate-organizer",
    rank: 58,
    category: "Consumer Admin",
    name: "Lost Password / Digital Estate Organizer",
    pain: "Families need to organize accounts and access info before crisis",
    price: "$29–$99",
    upsell: "$149 estate admin packet",
    targetCac: 20,
    score: 6.97,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 7,
    adSafe: 7,
    urgency: 8,
    noBrand: 6,
    aiFit: 8,
    compGap: 7,
    verdict: "Trust-sensitive but useful; avoid collecting passwords directly",
    metaAngle: "Create a digital account organizer and family instruction sheet",
    frontProd: "$39 digital binder",
    aiDeliv: "Accounts checklist, emergency access plan, family instructions",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "event-look-planner",
    rank: 59,
    category: "Beauty / Events",
    name: "Event Look Planner",
    pain: "People need outfit/hair/makeup plan for weddings, conferences, dates",
    price: "$19–$79",
    upsell: "Affiliate products; $99 premium stylist",
    targetCac: 20,
    score: 7.78,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 8,
    profit: 7,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 6,
    verdict: "Good visual creative and clear deadline-driven urgency",
    metaAngle: "Create a polished look plan for an upcoming event",
    frontProd: "$29 event look plan",
    aiDeliv: "Outfit formula, grooming checklist, shopping list, timeline",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "beginner-golf-improvement-plan",
    rank: 60,
    category: "Sports / Hobbies",
    name: "Beginner Golf Improvement Plan",
    pain: "Adults want to stop embarrassing themselves at golf outings",
    price: "$29–$99",
    upsell: "Affiliate lessons/equipment",
    targetCac: 20,
    score: 7.02,
    tier: "C - Needs Strong Angle",
    ease: 8,
    cacPred: 6,
    profit: 7,
    adSafe: 9,
    urgency: 6,
    noBrand: 7,
    aiFit: 8,
    compGap: 6,
    verdict: "Could work for male status/networking, but broader appeal is smaller",
    metaAngle: "Build a beginner golf improvement plan by schedule and goal",
    frontProd: "$39 golf starter plan",
    aiDeliv: "Practice plan, drills, etiquette cheat sheet, lesson checklist",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "airbnb-guest-ready-home-checklist",
    rank: 61,
    category: "Home / Cleaning",
    name: "Airbnb Guest-Ready Home Checklist",
    pain: "Hosts/homeowners need fast preparation for guests",
    price: "$19–$59",
    upsell: "Affiliate supplies; $99 premium",
    targetCac: 20,
    score: 7.45,
    tier: "B - Worth Testing",
    ease: 9,
    cacPred: 7,
    profit: 7,
    adSafe: 10,
    urgency: 6,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Safe and easy but may need niche angle for urgency",
    metaAngle: "Create a guest-ready home checklist and hosting setup plan",
    frontProd: "$29 guest-ready plan",
    aiDeliv: "Cleaning zones, supply list, room setup, timeline",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "spanish-learning-plan-for-travel",
    rank: 62,
    category: "Education / Adults",
    name: "Spanish Learning Plan for Travel",
    pain: "People want practical Spanish fast for trips/dating/work",
    price: "$19–$59",
    upsell: "$9/mo language assistant",
    targetCac: 20,
    score: 7.23,
    tier: "C - Needs Strong Angle",
    ease: 9,
    cacPred: 7,
    profit: 6,
    adSafe: 9,
    urgency: 6,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Easy but crowded; niche by travel or dating increases pull",
    metaAngle: "Create a practical Spanish plan for your trip or daily life",
    frontProd: "$29 language plan",
    aiDeliv: "30-day plan, phrases, practice scripts, daily schedule",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "traffic-ticket-prep-organizer",
    rank: 63,
    category: "Local Legal Admin",
    name: "Traffic Ticket Prep Organizer",
    pain: "Drivers want to understand options and organize court/payment deadlines",
    price: "$29–$79",
    upsell: "Attorney referral",
    targetCac: 15,
    score: 6.49,
    tier: "D - Search Only",
    ease: 7,
    cacPred: 5,
    profit: 7,
    adSafe: 5,
    urgency: 8,
    noBrand: 5,
    aiFit: 8,
    compGap: 7,
    verdict: "Useful but legal-adjacent; search intent much better than Meta",
    metaAngle: "Organize your traffic ticket details into a simple next-step packet",
    frontProd: "$39 ticket prep",
    aiDeliv: "Deadline extraction, question list, evidence checklist, court prep",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "storm-damage-documentation-kit",
    rank: 64,
    category: "Insurance / Home",
    name: "Storm Damage Documentation Kit",
    pain: "Homeowners need to document damage before claims/contractors",
    price: "$29–$99",
    upsell: "Contractor/public adjuster referral",
    targetCac: 20,
    score: 7.14,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 8,
    adSafe: 6,
    urgency: 9,
    noBrand: 6,
    aiFit: 8,
    compGap: 7,
    verdict: "Good around storm events; Meta can work if localized, compliance careful",
    metaAngle: "Create a storm-damage documentation checklist before calls and quotes",
    frontProd: "$49 documentation kit",
    aiDeliv: "Photo checklist, repair quote tracker, questions, timeline",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "couples-money-conversation-kit",
    rank: 65,
    category: "Personal Finance",
    name: "Couples Money Conversation Kit",
    pain: "Couples need structured money talks without fighting",
    price: "$19–$59",
    upsell: "$19/mo relationship finance assistant",
    targetCac: 15,
    score: 6.67,
    tier: "C - Needs Strong Angle",
    ease: 8,
    cacPred: 6,
    profit: 7,
    adSafe: 5,
    urgency: 7,
    noBrand: 6,
    aiFit: 8,
    compGap: 6,
    verdict: "Sensitive/personal-finance ad constraints; still emotionally strong",
    metaAngle: "Create a guided money conversation plan for couples",
    frontProd: "$29 money talk kit",
    aiDeliv: "Questions, budget template, values exercise, agenda",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "senior-scam-prevention-family-packet",
    rank: 66,
    category: "Seniors / Scams",
    name: "Senior Scam Prevention Family Packet",
    pain: "Families want to protect older relatives from scams",
    price: "$29–$99",
    upsell: "$199 family setup",
    targetCac: 20,
    score: 7.14,
    tier: "C - Needs Strong Angle",
    ease: 7,
    cacPred: 6,
    profit: 8,
    adSafe: 6,
    urgency: 9,
    noBrand: 5,
    aiFit: 8,
    compGap: 8,
    verdict: "Large pain with evidence, but trust-heavy and sensitive",
    metaAngle: "Create a scam-prevention plan for older family members",
    frontProd: "$49 prevention packet",
    aiDeliv: "Risk checklist, scripts, family rules, reporting links",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: "https://www.fbi.gov/news/press-releases/fbi-releases-annual-internet-crime-report"
  },
  {
    id: "tattoo-idea-artist-brief",
    rank: 67,
    category: "Local Services",
    name: "Tattoo Idea / Artist Brief",
    pain: "Consumers want a meaningful tattoo but need a clear brief for artists",
    price: "$19–$59",
    upsell: "Artist referral",
    targetCac: 20,
    score: 7.33,
    tier: "C - Needs Strong Angle",
    ease: 9,
    cacPred: 7,
    profit: 6,
    adSafe: 9,
    urgency: 6,
    noBrand: 8,
    aiFit: 8,
    compGap: 6,
    verdict: "Creative, visual, low compliance; moderate pain and price",
    metaAngle: "Turn a tattoo idea into a clear artist-ready brief",
    frontProd: "$29 tattoo brief",
    aiDeliv: "Concept board, symbolism, placement ideas, artist message",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "beginner-pickleball-plan",
    rank: 68,
    category: "Hobbies / Social",
    name: "Beginner Pickleball Plan",
    pain: "Adults want to improve fast and stop losing socially",
    price: "$19–$49",
    upsell: "Affiliate lessons/gear",
    targetCac: 15,
    score: 7.0,
    tier: "C - Needs Strong Angle",
    ease: 9,
    cacPred: 6,
    profit: 6,
    adSafe: 10,
    urgency: 5,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Fun but lower urgency; better as content/affiliate than paid CAC heavy",
    metaAngle: "Create a beginner improvement plan for pickleball",
    frontProd: "$29 skill plan",
    aiDeliv: "Drills, weekly schedule, gear basics, local court checklist",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "restaurant-ordering-plan-by-goal",
    rank: 69,
    category: "Food / Weight Adjacent",
    name: "Restaurant Ordering Plan by Goal",
    pain: "People want to eat out without derailing goals/budget",
    price: "$9–$39",
    upsell: "$9/mo assistant",
    targetCac: 10,
    score: 6.18,
    tier: "D - Search Only",
    ease: 9,
    cacPred: 6,
    profit: 5,
    adSafe: 6,
    urgency: 5,
    noBrand: 7,
    aiFit: 7,
    compGap: 4,
    verdict: "Low price/urgency; not ideal paid CAC unless tied to specific lifestyle niche",
    metaAngle: "Create a simple eating-out plan for your preferences and lifestyle",
    frontProd: "$19 dining plan",
    aiDeliv: "Menu strategy, go-to orders, social scripts",
    platforms: ["n8n", "GPT-4o"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "Barbell Framework: position as either the cheapest entry point or most specialized niche authority. Avoid the middle. Mechanism Building required before scaling ads.",
    acquisition: "Google search ads or outbound SMS. Intent-based traffic converts better than cold social.",
    source: ""
  },
  {
    id: "holiday-budget-gift-tracker",
    rank: 70,
    category: "Holidays",
    name: "Holiday Budget + Gift Tracker",
    pain: "Holiday shopping becomes expensive and chaotic",
    price: "$19–$59",
    upsell: "Affiliate products",
    targetCac: 20,
    score: 7.38,
    tier: "C - Needs Strong Angle",
    ease: 9,
    cacPred: 7,
    profit: 6,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Seasonal but Meta-friendly",
    metaAngle: "Create a holiday budget, gift list, and shopping timeline",
    frontProd: "$29 holiday plan",
    aiDeliv: "Gift tracker, budget, message drafts, shipping deadlines",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "home-sale-prep-checklist",
    rank: 71,
    category: "Real Estate / Sellers",
    name: "Home Sale Prep Checklist",
    pain: "Homeowners need to prepare before listing or meeting realtor",
    price: "$29–$99",
    upsell: "Realtor referral",
    targetCac: 20,
    score: 7.14,
    tier: "C - Needs Strong Angle",
    ease: 8,
    cacPred: 6,
    profit: 8,
    adSafe: 7,
    urgency: 8,
    noBrand: 6,
    aiFit: 8,
    compGap: 6,
    verdict: "Good partner/referral path; ad policy/housing category requires care",
    metaAngle: "Create a home sale readiness checklist before listing",
    frontProd: "$49 sale prep plan",
    aiDeliv: "Room-by-room prep, repair questions, staging list, realtor interview",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "Yes - high pain, phone responsive demographic",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "family-chore-system-builder",
    rank: 72,
    category: "Parenting / Chores",
    name: "Family Chore System Builder",
    pain: "Parents need a household system kids can follow",
    price: "$19–$59",
    upsell: "Printable templates/subscription",
    targetCac: 20,
    score: 7.38,
    tier: "C - Needs Strong Angle",
    ease: 9,
    cacPred: 7,
    profit: 6,
    adSafe: 9,
    urgency: 7,
    noBrand: 8,
    aiFit: 8,
    compGap: 5,
    verdict: "Simple and practical but needs a sharper pain hook",
    metaAngle: "Create a household chore system by age and schedule",
    frontProd: "$29 chore system",
    aiDeliv: "Chore chart, reward rules, weekly reset, family meeting agenda",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  },
  {
    id: "big-purchase-decision-matrix",
    rank: 73,
    category: "Finance / Shopping",
    name: "Big Purchase Decision Matrix",
    pain: "Consumers compare expensive options and fear regret",
    price: "$19–$59",
    upsell: "Affiliate/referrals",
    targetCac: 15,
    score: 7.05,
    tier: "C - Needs Strong Angle",
    ease: 9,
    cacPred: 6,
    profit: 6,
    adSafe: 9,
    urgency: 6,
    noBrand: 7,
    aiFit: 8,
    compGap: 6,
    verdict: "Too broad alone; niche it by car, wedding, home repair, electronics",
    metaAngle: "Compare big purchases with a personalized decision matrix",
    frontProd: "$29 decision matrix",
    aiDeliv: "Criteria, pros/cons, cost comparison, negotiation questions",
    platforms: ["n8n", "GPT-4o", "Stripe", "Typeform"],
    outboundViable: "No - ads to checkout preferred",
    coleGordon: "3S Formula: lead with Specificity + Speed + Simplicity. Name the exact problem, promise fast delivery, remove all friction to first transaction.",
    acquisition: "Meta ads with specific creative angle. Retargeting amplifies cold. Target CAC $35-$60.",
    source: ""
  }
];
